### ISSUE TITLE
problem installing setup.py

### ISSUE THREAD

**Issue by NicolaiThomassen** [ec-jrc/cbm#15]
Am i alone with this issue?
```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    long_description = fh.read()
  File "...\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 159: character maps to <undefined>
```

**Comment by NicolaiThomassen** [comment]
yes, it works wonders thanks. Did not get a notification that you answered to my issue so i continued by commenting the fh.read(). i pulled again and it works now. thanks

and i just installed in a venv with python setup.py install

**Comment by konanast** [comment]
Ok, nice to hear that it works now
